# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='Registree',
            new_name='registree',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='genre',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='registration',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='student_card_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
